"""empty message

Revision ID: 28456ce65480
Revises: 6563c7e0bb9a
Create Date: 2023-02-15 01:02:07.473495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28456ce65480'
down_revision = '6563c7e0bb9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flour', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('homo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('hetero', sa.String(length=255), nullable=True))
        batch_op.drop_column('copper')
        batch_op.drop_column('hypomelanistic')
        batch_op.drop_column('h_axanthic')
        batch_op.drop_column('rfp')
        batch_op.drop_column('leucistic')
        batch_op.drop_column('axanthic')
        batch_op.drop_column('h_melanoid')
        batch_op.drop_column('melanoid')
        batch_op.drop_column('h_copper')
        batch_op.drop_column('h_leucistic')
        batch_op.drop_column('h_albino')
        batch_op.drop_column('gdp')
        batch_op.drop_column('albino')
        batch_op.drop_column('h_hypomelanistic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('h_hypomelanistic', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('albino', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('gdp', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('h_albino', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('h_leucistic', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('h_copper', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('melanoid', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('h_melanoid', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('axanthic', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('leucistic', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('rfp', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('h_axanthic', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('hypomelanistic', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('copper', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('hetero')
        batch_op.drop_column('homo')
        batch_op.drop_column('flour')

    # ### end Alembic commands ###
