"""empty message

Revision ID: 6563c7e0bb9a
Revises: c39cc8eee0ee
Create Date: 2023-02-14 23:25:11.270235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6563c7e0bb9a'
down_revision = 'c39cc8eee0ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rfp', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('gdp', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('gdp')
        batch_op.drop_column('rfp')

    # ### end Alembic commands ###
