"""empty message

Revision ID: c39cc8eee0ee
Revises: b073cfc58082
Create Date: 2023-02-14 23:16:13.839209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c39cc8eee0ee'
down_revision = 'b073cfc58082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leucistic', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('melanoid', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('hypomelanistic', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('albino', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('copper', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('axanthic', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('h_leucistic', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('h_melanoid', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('h_hypomelanistic', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('h_albino', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('h_copper', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('h_axanthic', sa.String(length=255), nullable=True))
        batch_op.drop_column('sub_cat_albino')
        batch_op.drop_column('sub_cat_homo')
        batch_op.drop_column('sub_cat_melanoid')
        batch_op.drop_column('sub_cat_leucistic')
        batch_op.drop_column('sub_cat_wild')
        batch_op.drop_column('sub_cat_heter')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_cat_heter', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('sub_cat_wild', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('sub_cat_leucistic', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('sub_cat_melanoid', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('sub_cat_homo', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('sub_cat_albino', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('h_axanthic')
        batch_op.drop_column('h_copper')
        batch_op.drop_column('h_albino')
        batch_op.drop_column('h_hypomelanistic')
        batch_op.drop_column('h_melanoid')
        batch_op.drop_column('h_leucistic')
        batch_op.drop_column('axanthic')
        batch_op.drop_column('copper')
        batch_op.drop_column('albino')
        batch_op.drop_column('hypomelanistic')
        batch_op.drop_column('melanoid')
        batch_op.drop_column('leucistic')

    # ### end Alembic commands ###
