"""empty message

Revision ID: 7a570e9d32a4
Revises: 28aefeb10b11
Create Date: 2022-12-31 08:11:24.472354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7a570e9d32a4"
down_revision = "28aefeb10b11"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("additional_description", sa.String(length=1000), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_column("additional_description")

    # ### end Alembic commands ###
