"""empty message

Revision ID: b073cfc58082
Revises: 76734440f2fa
Create Date: 2023-02-06 16:06:02.631457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b073cfc58082'
down_revision = '76734440f2fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image3', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image3')
        batch_op.drop_column('image2')

    # ### end Alembic commands ###
